"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Web3Provider } from '@/components/ui/web3-provider';
import { NextPage } from "next";
import React, { FC, ReactNode } from "react";
import Link from "next/link";
import { ConnectKitButton } from 'connectkit';
import { useIndexer } from "@/hooks/useIndexer";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"

import {
  Card, CardContent
} from "@/components/ui/card"
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface LayoutProps {
  children?: ReactNode;
}

interface NavbarItemProps {
  link: string
  label: string
}

const NavbarItem: FC<NavbarItemProps> = ({ link, label }) => {
  return (<NavigationMenuItem>
    <Link href={link} legacyBehavior passHref>
      <NavigationMenuLink className={navigationMenuTriggerStyle()}>
        {label}
      </NavigationMenuLink>
    </Link>
  </NavigationMenuItem>)
}

const Layout: NextPage<LayoutProps> = ({ children }) => {
  useIndexer();

  return <>
    <nav>
      <Card className="max-w-5xl mx-auto mt-1">
        <CardContent className="p-6 mx-auto flex items-center justify-between">
          <NavigationMenu>
            <NavigationMenuList>
              <NavbarItem link="/" label="Home" />
              <NavbarItem link="/attestations" label="Attestations" />
              <NavbarItem link="/schemas" label="Schemas" />
            </NavigationMenuList>
          </NavigationMenu>
          <ConnectKitButton />
        </CardContent>
      </Card>
    </nav>
    <main>
      <div className="p-6 max-w-5xl mx-auto space-y-4">
        {children}
      </div>
    </main>
    <Toaster />
  </>
}

const Web3Wrapper: NextPage<LayoutProps> = ({ children }) => {
  return (
    <Web3Provider>
      <Layout>
        {children}
      </Layout>
    </Web3Provider>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Wrapper>
          {children}
        </Web3Wrapper>
      </body>
    </html>
  );
}
